name: Test Pull Request

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events for dev and main
  pull_request:
    branches: [ dev, main ]
  # Manual trigger e2e tests
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Run Cypress Tests'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs "serve and test"
  serve:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: deploy dist to localhost
        run: npx serve dist
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: run cypress tests
        run: ./node_modules/.bin/cypress run -- --baseUrl=https://localhost:5000
    
    
    
